version: '3.7'
services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/app
    ports:
      - "80:80"
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/app
    environment:
      PHP_IDE_CONFIG: serverName=${SERVER_NAME}
    env_file:
      - .env
    networks:
      default:
        ipv4_address: ${PHP_FPM_IP}
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: ${MYSQL_IP}
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
volumes:
  mysql_data: